/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/design-preview': RouteRecordInfo<
      '/admin/design-preview',
      '/admin/design-preview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/infra/file/': RouteRecordInfo<
      '/admin/infra/file/',
      '/admin/infra/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/infra/storage/': RouteRecordInfo<
      '/admin/infra/storage/',
      '/admin/infra/storage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/login': RouteRecordInfo<
      '/admin/login',
      '/admin/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/dept/': RouteRecordInfo<
      '/admin/system/dept/',
      '/admin/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/role/': RouteRecordInfo<
      '/admin/system/role/',
      '/admin/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/user/': RouteRecordInfo<
      '/admin/system/user/',
      '/admin/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/user/create': RouteRecordInfo<
      '/admin/system/user/create',
      '/admin/system/user/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/': RouteRecordInfo<
      '/app/',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/contacts/': RouteRecordInfo<
      '/app/contacts/',
      '/app/contacts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/docs/': RouteRecordInfo<
      '/app/docs/',
      '/app/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/invite/accept': RouteRecordInfo<
      '/app/invite/accept',
      '/app/invite/accept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/login': RouteRecordInfo<
      '/app/login',
      '/app/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/messages/': RouteRecordInfo<
      '/app/messages/',
      '/app/messages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/no-admin-access': RouteRecordInfo<
      '/app/no-admin-access',
      '/app/no-admin-access',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/register': RouteRecordInfo<
      '/app/register',
      '/app/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/tasks/': RouteRecordInfo<
      '/app/tasks/',
      '/app/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/design-preview.vue': {
      routes:
        | '/admin/design-preview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/infra/file/index.vue': {
      routes:
        | '/admin/infra/file/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/infra/storage/index.vue': {
      routes:
        | '/admin/infra/storage/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/login.vue': {
      routes:
        | '/admin/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/dept/index.vue': {
      routes:
        | '/admin/system/dept/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/role/index.vue': {
      routes:
        | '/admin/system/role/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/user/index.vue': {
      routes:
        | '/admin/system/user/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/user/create.vue': {
      routes:
        | '/admin/system/user/create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/index.vue': {
      routes:
        | '/app/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/contacts/index.vue': {
      routes:
        | '/app/contacts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/docs/index.vue': {
      routes:
        | '/app/docs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/invite/accept.vue': {
      routes:
        | '/app/invite/accept'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/login.vue': {
      routes:
        | '/app/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/messages/index.vue': {
      routes:
        | '/app/messages/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/no-admin-access.vue': {
      routes:
        | '/app/no-admin-access'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/register.vue': {
      routes:
        | '/app/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/tasks/index.vue': {
      routes:
        | '/app/tasks/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
