/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_deprecated/customers': RouteRecordInfo<
      '/_deprecated/customers',
      '/_deprecated/customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_deprecated/inbox': RouteRecordInfo<
      '/_deprecated/inbox',
      '/_deprecated/inbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_deprecated/settings': RouteRecordInfo<
      '/_deprecated/settings',
      '/_deprecated/settings',
      Record<never, never>,
      Record<never, never>,
      | '/_deprecated/settings/'
      | '/_deprecated/settings/members'
      | '/_deprecated/settings/notifications'
      | '/_deprecated/settings/security'
    >,
    '/_deprecated/settings/': RouteRecordInfo<
      '/_deprecated/settings/',
      '/_deprecated/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_deprecated/settings/members': RouteRecordInfo<
      '/_deprecated/settings/members',
      '/_deprecated/settings/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_deprecated/settings/notifications': RouteRecordInfo<
      '/_deprecated/settings/notifications',
      '/_deprecated/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_deprecated/settings/security': RouteRecordInfo<
      '/_deprecated/settings/security',
      '/_deprecated/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/design-preview': RouteRecordInfo<
      '/admin/design-preview',
      '/admin/design-preview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/infra/file/': RouteRecordInfo<
      '/admin/infra/file/',
      '/admin/infra/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/login': RouteRecordInfo<
      '/admin/login',
      '/admin/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/dept/': RouteRecordInfo<
      '/admin/system/dept/',
      '/admin/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/user/': RouteRecordInfo<
      '/admin/system/user/',
      '/admin/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/user/create': RouteRecordInfo<
      '/admin/system/user/create',
      '/admin/system/user/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/customers.vue': {
      routes:
        | '/_deprecated/customers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/inbox.vue': {
      routes:
        | '/_deprecated/inbox'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/settings.vue': {
      routes:
        | '/_deprecated/settings'
        | '/_deprecated/settings/'
        | '/_deprecated/settings/members'
        | '/_deprecated/settings/notifications'
        | '/_deprecated/settings/security'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/settings/index.vue': {
      routes:
        | '/_deprecated/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/settings/members.vue': {
      routes:
        | '/_deprecated/settings/members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/settings/notifications.vue': {
      routes:
        | '/_deprecated/settings/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/_deprecated/settings/security.vue': {
      routes:
        | '/_deprecated/settings/security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/design-preview.vue': {
      routes:
        | '/admin/design-preview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/infra/file/index.vue': {
      routes:
        | '/admin/infra/file/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/login.vue': {
      routes:
        | '/admin/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/dept/index.vue': {
      routes:
        | '/admin/system/dept/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/user/index.vue': {
      routes:
        | '/admin/system/user/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/system/user/create.vue': {
      routes:
        | '/admin/system/user/create'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
